Booking/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model_DB;

namespace WebBooking.Controllers
{
    public class BookingsController : Controller
    {
        private dat154_18_2Entities db = new dat154_18_2Entities();

        // GET: Bookings
        public async Task<ActionResult> Index()
        {
            var booking = db.Booking.Include(b => b.Customer).Include(b => b.Room1);
            return View(await booking.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = await db.Booking.FindAsync(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            ViewBag.customerID = new SelectList(db.Customer, "customerID", "navn");
            ViewBag.room = new SelectList(db.Room, "roomID", "roomID");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookingID,customerID,roomtype,checkinDate,checkoutDate,room")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Booking.Add(booking);
                await db.SaveChangesAsync();
                return RedirectToAction("YourAccount","Home");
            }

            ViewBag.customerID = new SelectList(db.Customer, "customerID", "navn", booking.customerID);
            ViewBag.room = new SelectList(db.Room, "roomID", "roomID", booking.room);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = await db.Booking.FindAsync(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.customerID = new SelectList(db.Customer, "customerID", "navn", booking.customerID);
            ViewBag.room = new SelectList(db.Room, "roomID", "roomID", booking.room);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookingID,customerID,roomtype,checkinDate,checkoutDate,room")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.customerID = new SelectList(db.Customer, "customerID", "navn", booking.customerID);
            ViewBag.room = new SelectList(db.Room, "roomID", "roomID", booking.room);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = await db.Booking.FindAsync(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Booking booking = await db.Booking.FindAsync(id);
            db.Booking.Remove(booking);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Booking/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model_DB;

namespace WebBooking.Controllers
{
    public class CustomersController : Controller
    {
        private dat154_18_2Entities db = new dat154_18_2Entities();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customer.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }


        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "customerID,navn,passord")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customer.Add(customer);
                db.SaveChanges();
                return RedirectToAction("YourAccount","Home",customer);
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "customerID,navn,passord")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customer.Find(id);
            db.Customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // get: Customers/Login/5
        [HttpPost,ActionName("Login")]
        public ActionResult Login(int? customerId)
        {

            if (customerId == null)
            {
                return RedirectToAction("Login", "Home", new { customerId = customerId, error = "Type in your Customer ID" });
            }
            Customer customer = db.Customer.Find(customerId);

            if (customer == null)
            {
                return RedirectToAction("Login", "Home", new { customerId = customerId, error = "Did not find user" });
            }
            customer.Booking = db.Booking.Select(booking => booking).Where(c => c.customerID == customer.customerID).ToList();
            return RedirectToAction("YourAccount","Home", customer);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Booking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Util;
using Model_DB;


namespace WebBooking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "About Fawlty Towers";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact Fawlty Towers";

            return View();
        }
        public ActionResult Login(int? id, string error)
        {
            ViewBag.Error = error;
            ViewBag.Message = "The login page";
            if (id == null)
                return View();
            else
                return View(id);
        }
        public ActionResult Signup()
        {
            ViewBag.Message = "The Signup page";

            return View();
        }
        public ActionResult YourAccount(Customer customer)
        {
            ViewBag.Message = "Your account.";
            ViewBag.Title = "Your account ";

            return View(customer);
        }
    }
}

Booking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Fawlty Towers is a family-owned hotel run by Basil and Sybil Fawlty. <br />
    Meet the fantastic and lovable staff of Polly and Manuel while you enjoy your stay at the English Riviera </p>

Booking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Torquay
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@fawltytowers.co.uk</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@fawltytowers.co.uk</a>
</address>

Booking/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Fawlty Towers";
}

<div class="jumbotron">
    <h1>Fawlty Towers</h1>
    <p class="lead">The greatest place to stay in the English riviera!</p>
    <p>Enjoy your stay with the greatest service!</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            <a href="/Home/Signup"> Sign up</a> today to book fast and easy!
        </p>
        <p></p>
    </div>
    <div class="col-md-4">
        <h2>Already have an account?</h2>
        <p><a href="/Home/Login">  Log in </a> to book your favourite room today!</p>
        <p></p>
    </div>
    <div class="col-md-4">
        <h2>Contact</h2>
        <p>For any questions about bookings, dietary needs or access, please <a href="/Home/Contact">contact us</a> for more information.</p>
        <p></p>
    </div>
</div>

Booking/Views/Home/Login.cshtml
@model Model_DB.Customer
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Login";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@using (Html.BeginForm("Login", "Customers"))
{

<div class="form-horizontal">
    <h4>Customer</h4>
    <hr />
    @if (ViewBag.Error != "")
    {
        <p>@ViewBag.Error</p>
    }
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.customerID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.customerID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.customerID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Booking/Views/Home/Signup.cshtml
@model Model_DB.Customer

@{
    ViewBag.Title = "Sign Up";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Customers"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.navn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.navn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.navn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.passord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.passord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.passord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Booking/Views/Home/YourAccount.cshtml
@model Model_DB.Customer
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Your Account";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<div>
    @if (Model != null)
    {
        <p>Welcome 
        @Html.DisplayFor(model => model.navn)
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Booking)
                </th>
            </tr>
            @foreach (var item in Model.Booking)
            {
                <tr>
                    @Html.DisplayForModel()
                </tr>
            <tr>
                @Html.DisplayFor(x => item.checkinDate)
            </tr>
            <tr>
                @Html.DisplayFor(x => item.checkoutDate)
            </tr>
            <tr>
                @Html.DisplayFor(x => item.roomtype)
            </tr>
                }

        </table>
        <div>
            @Html.ActionLink("New Booking", "Create", "Bookings")
        </div>
    }
    else
    {
        <p>Please <a href="/Home/Login">  Log in </a></p>
    }
</div>